# Copyright (c) 2025 Achraf BEN CHEIKH LADHARI
# Licensed under the MIT License.
# DO NOT REMOVE THIS LICENSE HEADER.

- name: License check
  hosts: localhost
  tasks:
    - name: Validate headers
      command: ../../validate.sh
      args:
        chdir: "{{ playbook_dir }}"